class DominosTester{
public static void main(String typeOfFood[]){
 String foodName = "farmhouse";
double priceOfFood=Dominos.search(foodName);
double priceWithGivenQuantity = Dominos.search("farmhouse",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity);

String foodName1 = "peppy paneer";
double priceOfFood1=Dominos.search(foodName1);
System.out.println("the ordered food is "+ priceOfFood1);
double priceWithGivenQuantity1 = Dominos.search("peppy paneer",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity1);

 String foodName2 = "margharita";
double priceOfFood2=Dominos.search(foodName2);
System.out.println("the ordered food is "+ priceOfFood2);
double priceWithGivenQuantity2 = Dominos.search("margharita",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity2);

String foodName3 = "tandoori paneer";
double priceOfFood3=Dominos.search(foodName3);
System.out.println("the ordered food is "+ priceOfFood3);
double priceWithGivenQuantity3 = Dominos.search("tandoori paneer",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity3);
 String foodName4 = "gourmet pizza";
double priceOfFood4=Dominos.search(foodName4);
System.out.println("the ordered food is "+ priceOfFood4);
double priceWithGivenQuantity4 = Dominos.search("gourmet pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity4);
 String foodName5= "veg pizza";
double priceOfFood5=Dominos.search(foodName5);
System.out.println("the ordered food is "+ priceOfFood5);
double priceWithGivenQuantity5 = Dominos.search("veg pizza",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity5);
String foodName6 = "paratha pizza";
double priceOfFood6=Dominos.search(foodName6);
System.out.println("the ordered food is "+ priceOfFood6);
double priceWithGivenQuantity6 = Dominos.search("paratha pizza",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity6);
String foodName7 = "pasta pizza";
double priceOfFood7=Dominos.search(foodName7);
System.out.println("the ordered food is "+ priceOfFood7);
double priceWithGivenQuantity7 = Dominos.search("pasta pizza",4);
System.out.println("the food with quantity"+ priceWithGivenQuantity7);
String foodName8= "cheese & corn";
double priceOfFood8=Dominos.search(foodName8);
System.out.println("the ordered food is "+ priceOfFood8);
double priceWithGivenQuantity8 = Dominos.search("cheese & corn",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity8);
String foodName9 = "paneer paratha pizza";
double priceOfFood9=Dominos.search(foodName9);
System.out.println("the ordered food is "+ priceOfFood9);
double priceWithGivenQuantity9 = Dominos.search("paneer paratha",5);
System.out.println("the food with quantity"+ priceWithGivenQuantity9);
String foodName10 = "mushrrom pizza";
double priceOfFood10=Dominos.search(foodName10);
System.out.println("the ordered food is "+ priceOfFood10);
double priceWithGivenQuantity10 = Dominos.search("mushroom pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity10);
String foodName11 = "mexican pizza";
double priceOfFood11=Dominos.search(foodName11);
System.out.println("the ordered food is "+ priceOfFood11);
double priceWithGivenQuantity11 = Dominos.search("mexican pizza",6);
System.out.println("the food with quantity"+ priceWithGivenQuantity11);
String foodName12 = "delux pizza";
double priceOfFood12=Dominos.search(foodName12);
System.out.println("the ordered food is "+ priceOfFood12);
double priceWithGivenQuantity12 = Dominos.search("delux pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity12);
String foodName13= "tomato pizza";
double priceOfFood13=Dominos.search(foodName13);
System.out.println("the ordered food is "+ priceOfFood13);
double priceWithGivenQuantity13 = Dominos.search("tomato pizza",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity13);
String foodName14 = "sausage pizza";
double priceOfFood14=Dominos.search(foodName14);
System.out.println("the ordered food is "+ priceOfFood14);
double priceWithGivenQuantity14 = Dominos.search("sausage pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity14);
String foodName15 = "Chicken pepperoni";
double priceOfFood15=Dominos.search(foodName15);
double priceWithGivenQuantity15 = Dominos.search("chicken pepperoni",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity15);
System.out.println("the ordered food is "+ priceOfFood15);
String foodName16 = "indi chicken";
double priceOfFood16=Dominos.search(foodName16);
System.out.println("the ordered food is "+ priceOfFood16);
double priceWithGivenQuantity16 = Dominos.search("indi chicken",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity16);
String foodName17 = "loaded non veg";
double priceOfFood17=Dominos.search(foodName17);
System.out.println("the ordered food is "+ priceOfFood17);
double priceWithGivenQuantity17 = Dominos.search("loaded non veg",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity17);
String foodName18 = " double chicken";
double priceOfFood18= Dominos.search(foodName18);
System.out.println("the ordered food is "+ priceOfFood18);
double priceWithGivenQuantity18 = Dominos.search("double chicken",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity18);
String foodName19 = "feast pizza";
double priceOfFood19=Dominos.search(foodName19);
System.out.println("the ordered food is "+ priceOfFood19);
double priceWithGivenQuantity19 = Dominos.search("feast pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity19);

}
}