class SwiggyTester{
public static void main(String typeOfFood[]){
 String foodName = "french fry";
double priceOfFood=Swiggy.search(foodName);
System.out.println("the ordered food is "+priceOfFood);
double priceWithGivenQuantity = Swiggy.search("french fries",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity);
String foodName1 = "fruit bowl";
double priceOfFood1=Swiggy.search(foodName1);
System.out.println("the ordered food is "+ priceOfFood1);
double priceWithGivenQuantity1 = Swiggy.search("fruit bowl",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity1);
 String foodName2 = "paratha";
double priceOfFood2=Swiggy.search(foodName2);
System.out.println("the ordered food is "+ priceOfFood2);
double priceWithGivenQuantity2 = Swiggy.search("paratha",4);
System.out.println("the food with quantity"+ priceWithGivenQuantity2);
String foodName3 = "chole bhature";
double priceOfFood3=Swiggy.search(foodName3);
System.out.println("the ordered food is "+ priceOfFood3);
double priceWithGivenQuantity3 = Swiggy.search("chole bhature",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity3);
 String foodName4 = "omelette";
double priceOfFood4=Swiggy.search(foodName4);
System.out.println("the ordered food is "+ priceOfFood4);
double priceWithGivenQuantity4 = Swiggy.search("omelette",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity4);
 String foodName5= "puri sabbji";
double priceOfFood5=Swiggy.search(foodName5);
System.out.println("the ordered food is "+ priceOfFood5);
double priceWithGivenQuantity5 = Swiggy.search("puri sabbji",4);
System.out.println("the food with quantity"+ priceWithGivenQuantity5);
String foodName6 = "egg bhurji";
double priceOfFood6=Swiggy.search(foodName6);
System.out.println("the ordered food is "+ priceOfFood6);
double priceWithGivenQuantity6 = Swiggy.search("egg bhurji",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity6);
String foodName7 = "curd rice";
double priceOfFood7=Swiggy.search(foodName7);
System.out.println("the ordered food is "+ priceOfFood7);
double priceWithGivenQuantity7 = Swiggy.search("curd rice",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity7);
String foodName8= "cheese maggie";
double priceOfFood8=Swiggy.search(foodName8);
System.out.println("the ordered food is "+ priceOfFood8);
double priceWithGivenQuantity8 = Swiggy.search("cheese maggie",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity8);
String foodName9 = "pav bhaji";
double priceOfFood9=Swiggy.search(foodName9);
System.out.println("the ordered food is "+ priceOfFood9);
double priceWithGivenQuantity9 = Swiggy.search("pav bhaji",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity9);
String foodName10 = "vada pav";
double priceOfFood10=Swiggy.search(foodName10);
System.out.println("the ordered food is "+ priceOfFood10);
double priceWithGivenQuantity10 = Swiggy.search("vada pav",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity10);
String foodName11 = "dhabeli";
double priceOfFood11=Swiggy.search(foodName11);
System.out.println("the ordered food is "+ priceOfFood11);
double priceWithGivenQuantity11 = Swiggy.search("dhabeli",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity11);
String foodName12 = "egg pav bhaji";
double priceOfFood12=Swiggy.search(foodName12);
System.out.println("the ordered food is "+ priceOfFood12);
double priceWithGivenQuantity12 = Swiggy.search("egg pav bhaji",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity12);
String foodName13= "kathi roll";
double priceOfFood13=Swiggy.search(foodName13);
System.out.println("the ordered food is "+ priceOfFood13);
double priceWithGivenQuantity13 = Swiggy.search("kathi roll",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity13);
String foodName14 = "mango milkshake";
double priceOfFood14=Swiggy.search(foodName14);
System.out.println("the ordered food is "+ priceOfFood14);
double priceWithGivenQuantity14 = Swiggy.search("mango milkshake",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity14);
String foodName15 = "fish tawa fry";
double priceOfFood15=Swiggy.search(foodName15);
System.out.println("the ordered food is "+ priceOfFood15);
double priceWithGivenQuantity15 = Swiggy.search("fish tawa fry",1);
System.out.println("the food with quantity"+ priceWithGivenQuantity15);
String foodName16 = "paneer butter masala";
double priceOfFood16=Swiggy.search(foodName16);
System.out.println("the ordered food is "+ priceOfFood16);
double priceWithGivenQuantity16 = Swiggy.search("paneer butter masala",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity16);
String foodName17 = "paneer tikka";
double priceOfFood17=Swiggy.search(foodName17);
System.out.println("the ordered food is "+ priceOfFood17);
double priceWithGivenQuantity17 = Swiggy.search("paneer tikka",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity17);
String foodName18 = "chicken tikka";
double priceOfFood18= Swiggy.search(foodName18);
System.out.println("the ordered food is "+ priceOfFood18);
double priceWithGivenQuantity18 = Swiggy.search("hicken tikka",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity18);
String foodName19 = "fish curry";
double priceOfFood19=Swiggy.search(foodName19);
System.out.println("the ordered food is "+ priceOfFood19);
double priceWithGivenQuantity19 = Swiggy.search("fish curry",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity19);

}
}