class ZomatoTester{
public static void main(String typeOfFood[]){
 String foodName = "pizza";
double priceOfFood=Zomato.search(foodName);
System.out.println("the ordered food is "+priceOfFood);
double priceWithGivenQuantity = Zomato.search("pizza",2);
System.out.println("the food with quantity"+ priceWithGivenQuantity);
String foodName1 = "biryani";
double priceOfFood1=Zomato.search(foodName1);
System.out.println("the ordered food is "+ priceOfFood1);
double priceWithGivenQuantity1= Zomato.search("burger",3);
System.out.println("the food with quantity"+ priceWithGivenQuantity1);
 String foodName2 = "burger";
double priceOfFood2=Zomato.search(foodName2);
System.out.println("the ordered food is "+ priceOfFood2);
double priceWithGivenQuantity2 = Zomato.search("burger",4);
System.out.println("the food with quantity"+ priceWithGivenQuantity2);
String foodName3 = "donut";
double priceOfFood3=Zomato.search(foodName3);
System.out.println("the ordered food is "+ priceOfFood3);
double priceWithGivenQuantity3 = Zomato.search("donut", 2);
System.out.println("the food with quantity"+ priceWithGivenQuantity3);
 String foodName4 = "noodles";
double priceOfFood4=Zomato.search(foodName4);
System.out.println("the ordered food is "+ priceOfFood4);
double priceWithGivenQuantity4 = Zomato.search("noodles",5);
System.out.println("the food with quantity"+ priceWithGivenQuantity4);
 String foodName5= "gobi chilly";
double priceOfFood5=Zomato.search(foodName5);
System.out.println("the ordered food is "+ priceOfFood5);
double priceWithGivenQuantity5 = Zomato.search("gobi chilly", 3);
System.out.println("the food with quantity"+ priceWithGivenQuantity5);
String foodName6 = "tandoori";
double priceOfFood6=Zomato.search(foodName6);
System.out.println("the ordered food is "+ priceOfFood6);
double priceWithGivenQuantity6 = Zomato.search("tandoori", 2);
System.out.println("the food with quantity"+ priceWithGivenQuantity6);
String foodName7 = "dosa";
double priceOfFood7=Zomato.search(foodName7);
System.out.println("the ordered food is "+ priceOfFood7);
double priceWithGivenQuantity7 = Zomato.search("dosa", 4);
System.out.println("the food with quantity"+ priceWithGivenQuantity7);
String foodName8= "chicken friedrice";
double priceOfFood8=Zomato.search(foodName8);
System.out.println("the ordered food is "+ priceOfFood8);
double priceWithGivenQuantity8 = Zomato.search("chicken friedrice", 2);
System.out.println("the food with quantity"+ priceWithGivenQuantity8);
String foodName9 = "babycorn chilly";
double priceOfFood9=Zomato.search(foodName9);
System.out.println("the ordered food is "+ priceOfFood9);
double priceWithGivenQuantity9 = Zomato.search("babycorn chilly", 4);
System.out.println("the food with quantity"+ priceWithGivenQuantity9);
String foodName10 = "pastries";
double priceOfFood10=Zomato.search(foodName10);
System.out.println("the ordered food is "+ priceOfFood10);
double priceWithGivenQuantity10 = Zomato.search("pastries", 5);
System.out.println("the food with quantity"+ priceWithGivenQuantity10);
String foodName11 = "roti curry";
double priceOfFood11=Zomato.search(foodName11);
System.out.println("the ordered food is "+ priceOfFood11);
double priceWithGivenQuantity11 = Zomato.search("roti curry", 4);
System.out.println("the food with quantity"+ priceWithGivenQuantity11);
String foodName12 = "cold coffee";
double priceOfFood12=Zomato.search(foodName12);
System.out.println("the ordered food is "+ priceOfFood12);
double priceWithGivenQuantity12 = Zomato.search("cold coffee", 2);
System.out.println("the food with quantity"+ priceWithGivenQuantity12);
String foodName13= "roll";
double priceOfFood13=Zomato.search(foodName13);
System.out.println("the ordered food is "+ priceOfFood13);
double priceWithGivenQuantity13 = Zomato.search("roll", 5);
System.out.println("the food with quantity"+ priceWithGivenQuantity13);
String foodName14 = "chilly momos";
double priceOfFood14=Zomato.search(foodName14);
System.out.println("the ordered food is "+ priceOfFood14);
double priceWithGivenQuantity14 = Zomato.search("chilly momos", 2);
System.out.println("the food with quantity"+ priceWithGivenQuantity14);
String foodName15 = "momos";
double priceOfFood15=Zomato.search(foodName15);
System.out.println("the ordered food is "+ priceOfFood15);
double priceWithGivenQuantity15 = Zomato.search("momos", 6);
System.out.println("the food with quantity"+ priceWithGivenQuantity15);

}
}